"""create_notification_metrics_table

Revision ID: 87062071874d
Revises: 0abc478caedc
Create Date: 2026-09-12 11:58:44.063449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87062071874d'
down_revision: Union[str, Sequence[str], None] = '0abc478caedc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_metrics_event_type'), 'notification_metrics', ['event_type'], unique=False)
    op.create_index(op.f('ix_notification_metrics_id'), 'notification_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_notification_metrics_timestamp'), 'notification_metrics', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_metrics_timestamp'), table_name='notification_metrics')
    op.drop_index(op.f('ix_notification_metrics_id'), table_name='notification_metrics')
    op.drop_index(op.f('ix_notification_metrics_event_type'), table_name='notification_metrics')
    op.drop_table('notification_metrics')
    # ### end Alembic commands ###
