"""add_unique_constraint_to_metrics

Revision ID: a6d6b0c07686
Revises: 87062071874d
Create Date: 2026-09-15 11:25:16.237155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6d6b0c07686'
down_revision: Union[str, Sequence[str], None] = '87062071874d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_event_timestamp', 'notification_metrics', ['event_type', 'timestamp'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_event_timestamp', 'notification_metrics', type_='unique')
    # ### end Alembic commands ###
